import React,{useState} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {ArrowLeft,ArrowUpRight,Plus,Box,Check,ShieldCheck,Wallet,LoaderCircle,TriangleAlert} from 'lucide-react';
import {toast} from 'sonner';
import {Input} from '../components/ui/input';
import {Textarea} from '../components/ui/textarea';
import {ActionButton} from '../components/Shared';
import {useWallet} from '../context/WalletContext';
import {api,errorMessage,colors,districtNames} from '../lib/api';
import {createToken,waitForConfirmation} from '../lib/transactions';
export default function Launch({reloadWorld}){
 const {wallet,provider,connect,authenticate}=useWallet(),navigate=useNavigate();
 const [form,setForm]=useState({name:'',symbol:'',supply:'1000000000',district:'meme',color:colors.meme,image:'',description:''}),[busy,setBusy]=useState(false),[step,setStep]=useState(''),[accepted,setAccepted]=useState(false),[pending,setPending]=useState(()=>{try{return JSON.parse(localStorage.getItem('nexus-pending-launch'));}catch{return null;}});
 const field=key=>e=>setForm({...form,[key]:e.target.value});
 const submit=async(e)=>{e.preventDefault();if(!wallet){connect();return;}setBusy(true);
  try{await authenticate();let payload=pending;
   if(!payload){setStep('Approve token creation in your wallet');await createToken(provider,wallet,form.supply,result=>{payload={...form,image:form.image || null,...result};delete payload.supply;localStorage.setItem('nexus-pending-launch',JSON.stringify(payload));setPending(payload);setStep('Waiting for Solana confirmation');});}
   else{setStep('Checking Solana confirmation');await waitForConfirmation(payload.signature);}
   setStep('Establishing your territory');const {data}=await api.post('/launches',payload);localStorage.removeItem('nexus-pending-launch');setPending(null);await reloadWorld();toast.success(`${data.symbol} has entered the world`);navigate(`/token/${data.id}`);
  }catch(e){toast.error(errorMessage(e));}finally{setBusy(false);setStep('');}
 };
 return <main className="content-page launch-page" data-testid="launch-page"><div className="page-breadcrumb"><Link to="/" data-testid="launch-back-world"><ArrowLeft size={15}/>Back to world</Link><span>/</span><span>New territory</span></div><div className="page-title-row"><div><div className="eyebrow">THE NEXT CHAPTER IS YOURS</div><h1 data-testid="launch-heading">Build your place.</h1><p>Create a token. Establish a territory. Bring your people.</p></div><span className="outline-badge"><span className="status-dot"/>SOLANA MAINNET</span></div>
 <div className="launch-layout"><form className="nexus-form launch-form" onSubmit={submit}><section><div className="form-section-title"><span>01</span><h2>Token identity</h2></div><div className="form-two-columns"><label>Token name<Input data-testid="launch-name" placeholder="Your token's name" value={form.name} onChange={field('name')} minLength={2} maxLength={40} required disabled={!!pending}/></label><label>Ticker<Input data-testid="launch-symbol" placeholder="TOKEN" value={form.symbol} onChange={e=>setForm({...form,symbol:e.target.value.toUpperCase()})} pattern="[A-Za-z0-9]+" maxLength={10} required disabled={!!pending}/></label></div><label>Token image URL <span>Optional</span><Input data-testid="launch-image" type="url" placeholder="https://…" value={form.image} onChange={field('image')} disabled={!!pending}/></label><label>Description <span>Optional</span><Textarea data-testid="launch-description" placeholder="A little about the world you're building." maxLength={1000} value={form.description} onChange={field('description')} disabled={!!pending}/></label><label>Total supply<Input data-testid="launch-supply" type="number" min="1" max="1000000000000" step="1" value={form.supply} onChange={field('supply')} required disabled={!!pending}/></label><div className="inline-info"><ShieldCheck size={14}/>Fixed supply · 6 decimals · No freeze authority</div></section>
 <section><div className="form-section-title"><span>02</span><h2>Choose your neighborhood</h2></div><div className="district-options">{Object.entries(districtNames).map(([id,name])=><button type="button" key={id} data-testid={`launch-district-${id}`} className={form.district===id?'selected':''} style={{'--district-color':colors[id]}} disabled={!!pending} onClick={()=>setForm({...form,district:id,color:colors[id]})}><span className="district-dot" style={{background:colors[id]}}/>{name}{form.district===id&&<Check size={14}/>}</button>)}</div><label>Building accent<div className="color-options">{Object.values(colors).map(color=><button type="button" key={color} data-testid={`launch-color-${color.slice(1)}`} disabled={!!pending} aria-label={`Building color ${color}`} className={form.color===color?'selected':''} style={{background:color}} onClick={()=>setForm({...form,color})}>{form.color===color&&<Check size={14}/>}</button>)}</div></label></section>
 <div className="launch-disclosure" data-testid="launch-disclosure"><TriangleAlert size={18}/><p>This creates a real SPL token on Solana mainnet and costs SOL. Token identity is stored in NEXUS. Creating a token does not create a liquidity pool or guarantee a trading route.</p></div><label className="checkbox-label"><input data-testid="launch-acknowledge" type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)} required/><span>I understand that on-chain transactions are irreversible.</span></label>
 {pending&&<div className="pending-launch" data-testid="pending-launch">A submitted launch is awaiting registration. Retry to finish without paying again.<small>{pending.signature}</small></div>}
 <ActionButton data-testid="launch-submit" type="submit" disabled={busy} className="full-width">{busy?<LoaderCircle className="spin" size={17}/>:wallet?<Plus size={17}/>:<Wallet size={17}/>}{busy?step:pending?'Complete registration':wallet?'Create token & enter the world':'Connect wallet to launch'}{!busy&&<ArrowUpRight size={17}/>}</ActionButton>
 </form><aside className="launch-preview"><div className="preview-scene" style={{'--building-color':form.color}}><div className="preview-grid"/><div className="css-building"><div className="building-top"/><div className="building-front">{Array.from({length:24},(_,i)=><span key={i}/>)}</div><div className="building-side"/></div><span className="preview-token" data-testid="launch-preview-symbol">{form.symbol || 'YOUR TOKEN'}</span><div className="preview-plot"/></div><div className="preview-details"><span className="eyebrow">YOUR FUTURE ADDRESS</span><h2 data-testid="launch-preview-name">{form.name || 'An idea. A building. A beginning.'}</h2><div><span>District</span><strong data-testid="launch-preview-district">{districtNames[form.district]}</strong></div><div><span>Network</span><strong>Solana mainnet</strong></div><div><span>Ownership</span><strong>Your wallet</strong></div></div><p className="preview-note">A small beginning. An unlimited skyline.</p></aside></div></main>;
}