import React,{useState,useEffect} from 'react';
import {useParams,Link} from 'react-router-dom';
import {ArrowLeft,ArrowUpRight,Copy,Check,Flag,Users,History,MessageSquare,Send,Globe,SlidersHorizontal} from 'lucide-react';
import {toast} from 'sonner';
import {api,errorMessage,money,price,shortAddress,districtNames} from '../lib/api';
import {useWallet} from '../context/WalletContext';
import {TokenAvatar,Change,Loading,Empty,ActionButton,ExternalLink} from '../components/Shared';
import {PriceChart} from '../components/PriceChart';
import {SwapPanel} from '../components/SwapPanel';
import {Input} from '../components/ui/input';
import {Textarea} from '../components/ui/textarea';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '../components/ui/dialog';

export default function TokenDashboard({reloadWorld}){
 const {id}=useParams(),[token,setToken]=useState(null),[error,setError]=useState(''),[tab,setTab]=useState('community'),[activity,setActivity]=useState([]),[bounties,setBounties]=useState([]),[post,setPost]=useState(''),[posting,setPosting]=useState(false),[copied,setCopied]=useState(false),[edit,setEdit]=useState(false),[presence,setPresence]=useState({description:'',image:'',color:'#b6f36e'}),[saving,setSaving]=useState(false);
 const {wallet,authenticate,connect}=useWallet();
 useEffect(()=>{let active=true;setToken(null);setError('');const load=async()=>{try{const {data}=await api.get(`/tokens/${id}`);if(active){setToken(data);setPresence({description:data.description || '',image:data.image || '',color:data.color || '#b6f36e'});}}catch(e){if(active)setError(errorMessage(e));}};load();const timer=setInterval(load,60000);return()=>{active=false;clearInterval(timer);};},[id]);
 const loadCommunity=()=>{api.get('/activity',{params:{token_id:id}}).then(r=>setActivity(r.data));api.get('/bounties',{params:{token_id:id}}).then(r=>setBounties(r.data));};
 useEffect(()=>{api.get('/activity',{params:{token_id:id}}).then(r=>setActivity(r.data)).catch(()=>{});api.get('/bounties',{params:{token_id:id}}).then(r=>setBounties(r.data)).catch(()=>{});},[id]);
 const sendPost=async(e)=>{e.preventDefault();setPosting(true);try{await authenticate();await api.post(`/tokens/${id}/community`,{content:post});setPost('');loadCommunity();toast.success('Message published');}catch(e){toast.error(errorMessage(e));}finally{setPosting(false);}};
 const copy=async()=>{try{await navigator.clipboard.writeText(token.mint);setCopied(true);setTimeout(()=>setCopied(false),2000);}catch{toast.error('Clipboard unavailable');}};
 const save=async(e)=>{e.preventDefault();setSaving(true);try{await authenticate();await api.patch(`/tokens/${id}/presence`,{...presence,image:presence.image || null});setToken({...token,...presence});setEdit(false);reloadWorld();toast.success('Territory updated');}catch(e){toast.error(errorMessage(e));}finally{setSaving(false);}};
 if(error)return <main className="content-page"><Empty icon={Globe} title={error} testId="token-error"><Link to="/" data-testid="token-error-back">Return to world</Link></Empty></main>;
 if(!token)return <main className="content-page"><Loading text="Entering the territory…"/></main>;
 return <main className="content-page token-page" data-testid="token-dashboard"><div className="page-breadcrumb"><Link to="/" data-testid="back-to-world"><ArrowLeft size={15}/>Back to world</Link><span>/</span><span data-testid="token-district">{districtNames[token.district]}</span><span>/</span><span>{token.symbol}</span></div>
 <div className="token-heading"><div className="token-heading-identity"><TokenAvatar token={token} size={60}/><div><div className="token-name-line"><h1 data-testid="token-name">{token.name}</h1><span className="ticker-badge" data-testid="token-ticker">{token.symbol}</span></div><button data-testid="copy-token-address" className="address-button" onClick={copy}>{shortAddress(token.mint)}{copied?<Check size={12}/>:<Copy size={12}/>}<span>Solana</span></button></div></div><div className="token-price"><strong data-testid="token-price">{price(token.price)}</strong><Change value={token.change_24h} testId="token-price-change"/><small>past 24 hours</small></div></div>
 <div className="token-stats">{[['Market cap',money(token.market_cap)],['24h volume',money(token.volume_24h)],['Liquidity',money(token.liquidity)],['Holders',token.holders?.toLocaleString() || 'Not available'],['24h buys / sells',token.buys_24h!=null?`${token.buys_24h.toLocaleString()} / ${token.sells_24h?.toLocaleString()}`:'—']].map(([name,value],i)=><div key={name}><small>{name}</small><strong data-testid={`token-stat-${i}`}>{value}</strong></div>)}</div>
 <div className="token-main-grid"><div className="token-main-content"><PriceChart token={token}/><div className="token-detail-tabs">{[['community','Community',MessageSquare],['bounties','Bounties',Flag],['about','Token information',Globe],['history','History',History]].map(([key,label,Icon])=><button key={key} data-testid={`token-tab-${key}`} className={tab===key?'active':''} onClick={()=>setTab(key)}><Icon size={15}/>{label}{key==='bounties'&&<span>{bounties.length}</span>}</button>)}</div>
 <section className="token-tab-content">{tab==='community'&&<><form className="community-form" onSubmit={sendPost}><Textarea data-testid="community-message-input" value={post} onChange={e=>setPost(e.target.value)} placeholder="What's happening in your territory?" minLength={10} maxLength={3000} required/><ActionButton data-testid="community-post-button" disabled={posting} type="submit"><Send size={14}/>{posting?'Publishing…':wallet?'Post message':'Connect & post'}</ActionButton></form>{activity.filter(a=>a.kind==='post').length?activity.filter(a=>a.kind==='post').map(a=><article className="community-message" key={a.id} data-testid={`community-message-${a.id}`}><span className="member-avatar">{a.wallet.slice(0,2)}</span><div><strong>{shortAddress(a.wallet)}</strong><time>{new Date(a.created_at).toLocaleString()}</time><p>{a.text}</p></div></article>):<Empty icon={MessageSquare} title="Make the first connection." text="No messages in this territory yet." testId="community-empty"/>}</>}
 {tab==='bounties'&&(bounties.length?<div className="token-bounties">{bounties.map(b=><Link key={b.id} data-testid={`token-bounty-${b.id}`} to={`/bounties?bounty=${b.id}`}><Flag size={19}/><span><strong>{b.name}</strong><small>{b.status} · {b.entries} entries</small></span><b>{b.reward} SOL</b><ArrowUpRight size={17}/></Link>)}</div>:<Empty icon={Flag} title="A territory full of possibilities." text="No bounties have been published for this token." testId="token-bounties-empty"><Link to={`/bounties?create=${id}`} data-testid="create-token-bounty" className="text-cta">Create a bounty <ArrowUpRight size={14}/></Link></Empty>)}
 {tab==='about'&&<div className="token-about" data-testid="token-about"><h2>About {token.name}</h2><p>{token.description}</p><dl><div><dt>Mint address</dt><dd className="break-address">{token.mint}</dd></div><div><dt>Network</dt><dd>Solana mainnet</dd></div><div><dt>District</dt><dd>{districtNames[token.district]}</dd></div><div><dt>Creator</dt><dd>{token.creator?shortAddress(token.creator):'External token'}</dd></div><div><dt>Market data</dt><dd>DEX Screener {token.market_updated_at&&`· ${new Date(token.market_updated_at).toLocaleTimeString()}`}</dd></div></dl><ExternalLink testId="token-solscan" href={`${process.env.REACT_APP_EXPLORER_URL}/token/${token.mint}`}>View on Solscan</ExternalLink>{wallet===token.creator&&<ActionButton data-testid="edit-territory" onClick={()=>setEdit(true)}><SlidersHorizontal size={15}/>Customize territory</ActionButton>}</div>}
 {tab==='history'&&(activity.filter(a=>a.kind!=='post').length?<div className="history-list">{activity.filter(a=>a.kind!=='post').map(a=><div key={a.id} data-testid={`token-history-${a.id}`}><span className="status-dot"/><span>{a.text}<small>{new Date(a.created_at).toLocaleString()}</small></span>{a.signature&&<ExternalLink testId={`history-tx-${a.id}`} href={`${process.env.REACT_APP_EXPLORER_URL}/tx/${a.signature}`}>Transaction</ExternalLink>}</div>)}</div>:<Empty icon={History} title="A new chapter in the world." text="Token launches and territory milestones will appear here." testId="history-empty"/>)}
 </section></div><aside className="token-trade-column"><SwapPanel token={token}/><div className="territory-summary" style={{'--territory-color':token.color}} data-testid="territory-summary"><div className="territory-grid"/><Flag size={22}/><small>YOUR NEXT DESTINATION</small><strong>{districtNames[token.district]}</strong><Link to="/" data-testid="explore-token-territory">Explore territory<ArrowUpRight size={15}/></Link></div></aside></div>
 <Dialog open={edit} onOpenChange={setEdit}><DialogContent className="nexus-dialog" data-testid="presence-dialog"><DialogTitle>Make it yours.</DialogTitle><DialogDescription>Customize your token's presence.</DialogDescription><form className="nexus-form" onSubmit={save}><label>Territory color<input data-testid="presence-color" type="color" value={presence.color} onChange={e=>setPresence({...presence,color:e.target.value})}/></label><label>Image URL<Input data-testid="presence-image" type="url" value={presence.image} onChange={e=>setPresence({...presence,image:e.target.value})}/></label><label>Description<Textarea data-testid="presence-description" value={presence.description} maxLength={1000} onChange={e=>setPresence({...presence,description:e.target.value})}/></label><ActionButton data-testid="save-presence" disabled={saving}>{saving?'Saving…':'Save territory'}</ActionButton></form></DialogContent></Dialog>
 </main>;
}