import React,{useRef,useState,useEffect} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {Globe2,Plus,Minus,LocateFixed,RotateCw,Layers,Maximize,Map,Box,ArrowUpRight,ChevronRight,Radio,Flag,Trophy,Activity,Compass,ChevronDown,Eye,EyeOff,X} from 'lucide-react';
import {CityCanvas} from '../world/CityCanvas';
import {IconButton,TokenAvatar,Change,ActionButton,Loading} from '../components/Shared';
import {money,api,colors} from '../lib/api';
const districts=[{id:'all',name:'All districts',color:'#dce9df'},{id:'meme',name:'Meme Quarter',color:colors.meme,x:-38,z:-25},{id:'defi',name:'DeFi Heights',color:colors.defi,x:34,z:-28},{id:'ai',name:'Neural District',color:colors.ai,x:35,z:35},{id:'culture',name:'The Waterfront',color:colors.culture,x:-38,z:36}];
export default function World({world,loading,error,reload}){
 const navigate=useNavigate(),city=useRef(),[district,setDistrict]=useState('all'),[layers,setLayers]=useState({labels:true,territories:true}),[layerOpen,setLayerOpen]=useState(false),[top,setTop]=useState(false),[camera,setCamera]=useState({x:0,z:0,zoom:1}),[tab,setTab]=useState('market'),[bounties,setBounties]=useState([]),[activity,setActivity]=useState([]),[panel,setPanel]=useState(true);
 const tokens=world?.tokens || [],leaders=[...tokens].filter(t=>district==='all'||t.district===district).sort((a,b)=>(b.market_cap||0)-(a.market_cap||0)).slice(0,4);
 useEffect(()=>{api.get('/bounties').then(r=>setBounties(r.data)).catch(()=>{});api.get('/activity').then(r=>setActivity(r.data)).catch(()=>{});},[]);
 const choose=d=>{setDistrict(d.id);d.id==='all'?city.current?.reset():city.current?.focus(d.x,d.z);};
 const fullscreen=()=>{if(document.fullscreenElement)document.exitFullscreen?.();else document.documentElement.requestFullscreen?.().catch(()=>{});};
 return <main className="world-page" data-testid="world-page">
 <CityCanvas ref={city} tokens={tokens} onSelect={id=>navigate(`/token/${id}`)} district={district} layers={layers} onCamera={setCamera}/>
 <div className="world-vignette"/>
 <div className="world-heading"><div className="eyebrow" data-testid="world-coordinate-label"><span className="status-dot"/>WORLD 001 <span>/</span> SOLANA MAINNET</div><h1 data-testid="world-title">A market. A metropolis.</h1><div className="world-caption" data-testid="world-caption">Every token has a place.</div></div>
 {loading&&!tokens.length&&<div className="world-loading"><Loading text="Entering the world…"/></div>}
 {error&&<div className="world-error" data-testid="world-error">The city couldn't load.<button data-testid="retry-world" onClick={reload}>Try again</button></div>}
 <div className="left-tools glass"><IconButton icon={Globe2} label="Explore the world" data-testid="world-explore-control" className="selected" onClick={()=>{setDistrict('all');city.current?.reset();}}/><IconButton icon={Trophy} label="Leaderboard" data-testid="world-leaderboard-control" onClick={()=>navigate('/leaderboard')}/><IconButton icon={Flag} label="Bounty board" data-testid="world-bounty-control" onClick={()=>navigate('/bounties')}/><span className="tool-divider"/><IconButton icon={Layers} label="Map layers" data-testid="world-layers-control" className={layerOpen?'selected':''} onClick={()=>setLayerOpen(!layerOpen)}/></div>
 {layerOpen&&<div className="layers-panel glass" data-testid="map-layers-panel"><strong>Map layers</strong>{['labels','territories'].map(key=><button key={key} data-testid={`toggle-${key}`} onClick={()=>setLayers({...layers,[key]:!layers[key]})}>{layers[key]?<Eye size={16}/>:<EyeOff size={16}/>} {key==='labels'?'Token labels':'Territory borders'}<span className={layers[key]?'toggle on':'toggle'}/></button>)}</div>}
 {panel?<aside className="world-sidebar"><section className="pulse-panel glass" data-testid="world-pulse-panel"><div className="panel-heading"><span><Activity size={16}/>World pulse</span><button aria-label="Hide world pulse" data-testid="hide-world-pulse" onClick={()=>setPanel(false)}><Minus size={16}/></button></div><div className="pulse-stats"><div><small>WORLD MARKET CAP</small><strong data-testid="world-market-cap">{money(world?.stats?.market_cap)}</strong></div><span className="live-badge" data-testid="market-source-badge"><span className="status-dot"/>ON-CHAIN WORLD</span></div><div className="pulse-minor"><span>24h volume<strong data-testid="world-volume">{money(world?.stats?.volume_24h)}</strong></span><span>Token buildings<strong data-testid="world-token-count">{tokens.length.toString().padStart(2,'0')}</strong></span></div><div className="panel-tabs"><button data-testid="pulse-market-tab" className={tab==='market'?'active':''} onClick={()=>setTab('market')}>City leaders</button><button data-testid="pulse-activity-tab" className={tab==='activity'?'active':''} onClick={()=>setTab('activity')}>Activity</button><span className="status-dot"/></div><div className="pulse-leaders">{tab==='market'?leaders.map((t,i)=><button key={t.id} data-testid={`leader-token-${t.id}`} onClick={()=>navigate(`/token/${t.id}`)}><span className="rank">0{i+1}</span><TokenAvatar token={t} size={30}/><span className="leader-identity"><strong>{t.symbol}</strong><small>{money(t.market_cap)}</small></span><Change value={t.change_24h} testId={`leader-change-${t.id}`}/></button>):activity.length?activity.slice(0,4).map(a=><Link data-testid={`world-activity-${a.id}`} to={`/token/${a.token_id}`} key={a.id} className="activity-mini"><span className="status-dot"/>{a.text}</Link>):<div className="pulse-empty" data-testid="world-activity-empty"><Radio size={21}/><p>The next chapter is yours.</p><small>No community activity yet.</small></div>}</div><Link to="/leaderboard" className="panel-footer-link" data-testid="view-leaderboard">View leaderboard<ArrowUpRight size={14}/></Link></section>
 <section className="bounty-peek glass"><div className="panel-heading"><span><Flag size={15}/>Bounty board</span><span className="small-count" data-testid="world-bounty-count">{world?.stats?.bounties || 0}</span></div>{bounties.filter(b=>b.status==='open').length?bounties.filter(b=>b.status==='open').slice(0,2).map(b=><Link data-testid={`world-bounty-${b.id}`} className="bounty-mini" to={`/bounties?bounty=${b.id}`} key={b.id}><span>{b.name}<small>{b.token_symbol} territory</small></span><strong>{b.reward} SOL</strong></Link>):<div className="bounty-peek-empty" data-testid="bounty-board-empty"><span className="bounty-crosshair"><Flag size={19}/></span><span>Unclaimed possibilities.<small>The first bounty starts with you.</small></span></div>}<Link to="/bounties" className="panel-footer-link" data-testid="explore-bounties">Explore bounties<ArrowUpRight size={14}/></Link></section>
 <Link to="/launch" className="launch-city-button" data-testid="launch-token-world"><Plus size={18}/><span>Build your place in the world<small>Launch a token</small></span><ArrowUpRight size={18}/></Link></aside>:<IconButton className="restore-panel glass" icon={Activity} label="Show world pulse" data-testid="show-world-pulse" onClick={()=>setPanel(true)}/>}
 <div className="map-compass" data-testid="map-compass"><span>N</span><Compass size={37} strokeWidth={1}/></div>
 <div className="minimap glass" data-testid="world-minimap"><svg viewBox="0 0 190 126" aria-label="City overview">{Array.from({length:10},(_,i)=><path key={i} d={`M ${i*20} 0 V 126 M 0 ${i*16} H 190`} stroke="#34413c" strokeWidth=".5"/>)}{tokens.map(t=><rect key={t.id} x={95+t.x*.9} y={63+t.z*.65} width={3} height={3} fill={t.color}/>)}<rect x={57+camera.x*.5} y={35+camera.z*.3} width={76/camera.zoom} height={53/camera.zoom} fill="#b6f36e09" stroke="#b6f36e" strokeWidth="1"/><circle cx="95" cy="63" r="2" fill="#b6f36e"/></svg><div><span>NEXUS CITY</span><span data-testid="camera-coordinates">{camera.x}, {camera.z}</span></div></div>
 <div className="district-dock glass" data-testid="district-dock">{districts.map(d=><button key={d.id} data-testid={`district-${d.id}`} onClick={()=>choose(d)} className={district===d.id?'active':''}>{d.id==='all'?<Globe2 size={15}/>:<span style={{background:d.color}} className="district-dot"/>}{d.name}</button>)}</div>
 <div className="map-controls"><div className="view-toggle glass"><button data-testid="view-3d" className={!top?'active':''} onClick={()=>{setTop(false);city.current?.view(false);}}><Box size={14}/>3D</button><button data-testid="view-top" className={top?'active':''} onClick={()=>{setTop(true);city.current?.view(true);}}><Map size={14}/>Top</button></div><div className="navigation-controls glass"><IconButton icon={Plus} label="Zoom in" data-testid="zoom-in" onClick={()=>city.current?.zoom(1)}/><IconButton icon={Minus} label="Zoom out" data-testid="zoom-out" onClick={()=>city.current?.zoom(-1)}/><span className="tool-divider"/><IconButton icon={LocateFixed} label="Recenter city" data-testid="recenter-city" onClick={()=>{city.current?.reset();setDistrict('all');setTop(false);}}/><IconButton icon={RotateCw} label="Rotate city" data-testid="rotate-city" onClick={()=>city.current?.rotate()}/><IconButton icon={Maximize} label="Toggle full screen" data-testid="fullscreen-city" onClick={fullscreen}/></div></div>
 <footer className="world-status"><span data-testid="world-status"><span className="status-dot"/>WORLD ONLINE <span className="footer-separator">/</span> {tokens.length} buildings <span className="footer-separator">/</span> 4 districts</span><span className="world-footer-center">MARKET CAP SHAPES THE SKYLINE</span><span data-testid="market-update-time">{world?.updated_at?`Market data · ${new Date(world.updated_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}`:'Awaiting market data'}<span className="footer-separator">/</span>UTC {new Date().toISOString().slice(11,16)}</span></footer>
 </main>;
}